train_dataloader:
  dataset:
    return_masks: False
    transforms:
      ops:
        - { type: CLAHEEnhance, p: 0.4, clip_limit: 3.0 }
        - { type: NBISimulation, p: 0.3, blue_factor: 1.5, green_factor: 1.2 }
        - { type: RandomColorJitter, p: 0.3, brightness: 0.3, contrast: 0.3 }
        - { type: RandomEqualize, p: 0.3 }
        #
        - { type: RandomPhotometricDistort, p: 0.4 }
        - { type: RandomZoomOut, fill: 0, p: 0.4 }
        - { type: RandomIoUCrop, p: 0.6 }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: RandomHorizontalFlip, p: 0.5 }
        - { type: Resize, size: [640, 640] }
        - { type: SanitizeBoundingBoxes, min_size: 1 }
        - { type: ConvertPILImage, dtype: "float32", scale: True }
        - { type: ConvertBoxes, fmt: "cxcywh", normalize: True }
  collate_fn:
    type: BatchImageCollateFuncion
    scales: [416, 480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800]
  shuffle: True
  num_workers: 4
  # total_batch_size: 14
  total_batch_size: 18 # 20

val_dataloader:
  dataset:
    transforms:
      ops:
        - { type: Resize, size: [640, 640] }
        - { type: ConvertPILImage, dtype: "float32", scale: True }
  shuffle: False
  # total_batch_size: 10
  total_batch_size: 20 # 18
  num_workers: 2
