use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000

epoches: 10
clip_max_norm: 0.1
# early_stop_patience: 10

optimizer:
  type: AdamW
  params:
    - params: "^(?=.*backbone)(?!.*(?:norm|bn)).*$"
      lr: 0.00001
    - params: "^(?=.*backbone)(?=.*(?:norm|bn)).*$"
      weight_decay: 0.
      lr: 0.00001
    - params: "^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$"
      weight_decay: 0.
    - params: ".*transformer.*"
      lr: 0.00005
    - params: ".*head.*"
      lr: 0.00005

  lr: 0.00005 # 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001 # 0.0001

lr_scheduler:
  # type: MultiStepLR
  # milestones: [1000]
  # gamma: 0.1
  # ----------------------
  type: CosineAnnealingLR
  T_max: 10
  eta_min: 0.000001
  # ----------------------
  # type: CosineAnnealingWarmRestarts
  # T_0: 10
  # T_mult: 1
  # eta_min: 1e-6

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 200 # 500
  # warmup_duration: 2000
